apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-begining-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 172.16.5.133
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-begining-service
                port:
                  number: 8000
          - path: /grpc
            pathType: Prefix
            backend:
              service:
                name: k8s-begining-service
                port:
                  number: 9000
