apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace-dev.yaml
  - ../../base/kratos-base.yaml
  - ../../base/microservice-base.yaml
  - ../../secrets/dev-kratos.yaml

namePrefix: dev-
namespace: kratos-dev
images:
  - name: oryd/kratos
    newTag: "dev-latest"
patchesStrategicMerge:
  - kratos-patch.yaml
  - microservice-patch.yaml
commonLabels:
  env: dev
