apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace-dev.yml
  - ../../base/kratos-base.yml
  - ../../base/microservice-base.yml
  - ../../secrets/dev-kratos.yml

namePrefix: dev-
namespace: kratos-dev
images:
  - name: oryd/kratos
    newTag: "dev-latest"
patches:
  - path: kratos-patch.yml
  - path: microservice-patch.yml
labels:
  - pairs:
      app: dev
