apiVersion: k8s.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-begining-dev
resources:
  - ../../../base
patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
images:
  - name: anhle3532/k8s-begining
    newTag: dev-latest # Set by CICD
