apiVersion: v2
name: k8s-begining
description: A Helm chart for beginning Kubernetes resources
type: application
version: 0.1.7
appVersion: 1.0.7
dependencies:
  - name: common
    version: 0.1.3
    repository: file://./charts/common
  - name: postgresql
    version: 16.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
