apiVersion: v2
name: k8s-begining
description: A Helm chart for beginning Kubernetes resources
type: application
version: 0.1.8
appVersion: 1.0.7
dependencies:
  - name: common
    version: 0.1.3
    repository: file://../common
  - name: timescaledb-single
    version: 0.33.1
    repository: https://charts.timescale.com
    condition: timescaledb-single.enabled
