apiVersion: v2
name: k8s-begining
description: A Helm chart for beginning Kubernetes resources
type: application
version: 0.1.1
appVersion: 1.0.1
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
