replicaCount: 1

image:
  repository: anhle3532/k8s-begining
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: "k8s-begining"

containerPort:
  http: 8000
  grpc: 9000

service:
  http:
    port: 8000
  grpc:
    port: 9000
  type: ClusterIP

secretName: k8s-begining-secret

timescaledb-single:
  enabled: true
  image:
    tag: pg16.2-ts2.14.2
  secrets:
    credentials:
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_USERNAME: standby
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_USERNAME: anh_admin
      PATRONI_admin_PASSWORD: anh_admin
  patroni:
    bootstrap:
      dcs:
        postgresql:
          parameters:
            max_connections: 100

appConfig: |
  server:
    http:
      addr: 0.0.0.0:${HTTP_PORT}
      timeout: 10s
    grpc:
      addr: 0.0.0.0:${GRPC_PORT}
      timeout: 10s

  data:
    database:
      driver: pgx
      source: ${DB_SOURCE}
    redis:
      addr: ${REDIS_ADDR}
      read_timeout: 0.2s
      write_timeout: 0.2s

ingress:
  enabled: false
  className: ""
  host: ""
