replicaCount: 1

image:
  repository: anhle3532/k8s-begining
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: "k8s-begining-dev"

containerPort:
  http: 8000
  grpc: 9000

service:
  http:
    port: 8000
  grpc:
    port: 9000
  type: ClusterIP

secretName: k8s-begining-secret

appConfig: |
  server:
    http:
      addr: 0.0.0.0:${HTTP_PORT}
      timeout: 10s
    grpc:
      addr: 0.0.0.0:${GRPC_PORT}
      timeout: 10s

  data:
    database:
      driver: pgx
      source: ${DB_SOURCE}
    redis:
      addr: ${REDIS_ADDR}
      read_timeout: 0.2s
      write_timeout: 0.2s

ingress:
  enabled: false
  className: ""
  host: ""
