apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespace-prod.yml
  - ../../base/kratos-base.yml
  - ../../base/microservice-base.yml
  - ../../secrets/prod-kratos.yml

namePrefix: prod-
namespace: kratos-prod
images:
  - name: oryd/kratos
    newTag: "prod-latest"
patches:
  - path: kratos-patch.yml
  - path: microservice-patch.yml
labels:
  - pairs:
      app: prod
