{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "common.fullname" . }}-ingress
    annotations:
        kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
    rules:
        - host: {{ .Values.ingress.host }}
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: {{ include "common.fullname" . }}-service
                        port:
                            number: {{ .Values.service.http.port }}
{{- end}}
{{- end -}}