{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
    name: {{ include "common.fullname" . }}-service
spec:
    selector:
        app: {{ include "common.fullname" . }}
    ports:
        - name: http
          port: {{ .Values.service.http.port }}
          targetPort: http
        - name: grpc
          port: {{ .Values.service.grpc.port }}
          targetPort: grpc
{{- end -}}