apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../../infrastructure/dev

patchesStrategicMerge:
  - config.yml

configMapGenerator:
  - name: k8s-begining-config
    files:
      - config.yml

images:
  - name: anhle3532/k8s-begining
    newTag: dev-latest
