apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: k8s-begining-es
spec:
    refreshInterval: 1m
    secretStoreRef:
        name: vault-backend
        kind: SecretStore
    target:
        name: k8s-begining-secret
        creationPolicy: Owner
    data:
        - secretKey: config.yaml
          remoteRef:
            key: secret/data/dev/k8s-begining
            property: config.yaml
