apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: k8s-begining-secret-store
spec:
    refreshInterval: 10
    secretStoreRef:
        name: vault-backend
        kind: SecretStore
    target:
        name: k8s-begining-secret
        creationPolicy: Owner
    data:
        - secretKey: config.yaml
          remoteRef:
            key: secret/data/dev/k8s-begining
            property: config.yaml
