{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "k8s-begining.fullname" . }}-config
data:
{{- range $name, $content := .Values.config.files }}
    {{ $name }}: |
        {{- $content | toString | nindent 4 }}
{{- end }}
{{- end }}
