apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "k8s-begining.fullname" . }}
spec:
    replicas: {{ .Values.replicaCount}}
    selector:
        matchLabels:
            app: {{ include "k8s-begining.name" . }}
    template:
        metadata:
            labels:
                app: {{ include "k8s-begining.name" . }}
            annotations:
                reloader.stakater.com/auto: "true"
        spec:
            containers:
                - name: k8s-begining-service
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}

                  command: ["/bin/sh", "-c"]
                  args:
                    - |
                      if [ -f /app/configs/config.tpl ]; then \
                        sed -e "s|\${HOST}|$HOST|g" \
                            -e "s|\${PORT}|$PORT|g" \
                            -e "s|\${DB_USER}|$DB_USER|g" \
                            -e "s|\${DB_PASS}|$DB_PASS|g" \
                            -e "s|\${DBNAME}|$DBNAME|g" \
                            /app/configs/config.tpl > /tmp/config.yaml; \
                      else \
                        echo "Config template not found"; \
                      fi && \
                      /app/k8s-begining -conf /tmp/config.yaml

                  ports:
                    - name: http
                      containerPort: {{ .Values.service.http.port }}
                    - name: grpc
                      containerPort: {{ .Values.service.grpc.port }}

                  env:
                    {{- range .Values.env }}
                    - name: {{ .name }}
                      value: "{{ .value }}"
                    {{- end }}
                    {{- if .Values.vault.enabled }}
                    - name: HOST
                      valueFrom:
                        secretKeyRef:
                          name: k8s-begining-db-creds
                          key: host
                    - name: PORT
                      valueFrom:
                        secretKeyRef:
                          name: k8s-begining-db-creds
                          key: port
                    - name: DBNAME
                      valueFrom:
                        secretKeyRef:
                          name: k8s-begining-db-creds
                          key: dbname
                    - name: DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: k8s-begining-db-creds
                          key: username
                    - name: DB_PASS
                      valueFrom:
                        secretKeyRef:
                          name: k8s-begining-db-creds
                          key: password
                    {{- end }}

                  {{- if .Values.secret }}
                  envFrom:
                    - secretRef:
                        name: {{ include "k8s-begining.fullname" . }}-secret
                  {{- end }}

                  volumeMounts:
                    - name: config
                      mountPath: /app/configs
                      readOnly: true

                  resources:
                    {{- toYaml .Values.resources | nindent 20 }}

                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: http
                    initialDelaySeconds: 5
                    periodSeconds: 10

                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: http
                    initialDelaySeconds: 15
                    periodSeconds: 20

            volumes:
                - name: config
                  configMap:
                    name: {{ include "k8s-begining.fullname" . }}-config
