{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-begining.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
