apiVersion: v1
kind: Service
metadata:
    name: {{ include "k8s-begining.fullname" . }}
spec:
    type: {{ .Values.service.type }}
    selector:
        app: {{ include "k8s-begining.name" . }}
    ports:
        - name: http
          port: {{ .Values.service.http.port }}
          targetPort: http
        - name: grpc
          port: {{ .Values.service.grpc.port }}
          targetPort: grpc
