apiVersion: v2
name: reloader
description: A Helm chart for Reloader - Watch and Reload Pods on ConfigMap or Secret change
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: reloader
    version: 1.0.60
    repository: https://stakater.github.io/stakater-charts