apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-begining-config
data:
  config.yml: |
    server:
      http:
        addr: 0.0.0.0:8000
      grpc:
        addr: 0.0.0.0:9000
    log:
      level: debug
