apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-begining
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-begining
  template:
    metadata:
      labels:
        app: k8s-begining
    spec:
      containers:
        - name: app
          image: anhle3532/k8s-begining:30b1f368
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: grpc
          env:
            - name: ENV
              value: dev
          volumeMounts:
            - name: config
              mountPath: /app/configs
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: k8s-begining-config
