image:
  repository: anhle3532/k8s-begining
  tag: dev-latest
  pullPolicy: Always

replicaCount: 1

env:
  ENV: dev

config:
  files:
    config.yml: |
      server:
        http:
          addr: 0.0.0.0:8000
        grpc:
          addr: 0.0.0.0:9000
      log:
        level: debug
