apiVersion: v1
kind: Service
metadata:
  name: k8s-begining-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-begining
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
